### ISSUE TITLE
openshift gets no-go and an exception when status of csr is blank

### ISSUE THREAD

**Issue by qiliRedHat** [cloud-bulldozer/cerberus#138] opened 2021-05-07 14:37 UTC
**Problem Description**
I run cerberus against openshift 4.8. I got a no-go and an exception when the `status` of  csr is blank.

**Expected**
I've not figured out why the `status` of my csr is blank, I'll try to reproduce it and add what I found to this issue. However, I red the document https://docs.openshift.com/container-platform/3.11/install_config/redeploying_certificates.html#cert-expiry-approving-csrs, it seems to me in some case the `status` of the certifications could be blank. 
> Approve all pending CSRs:

>$ oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' | xargs oc adm certificate approve
I think cerberus should be able to handle this situation, avoid the exception and provide some logs.

**Details**
Exception I got from cerberus output
```
2021-05-07 17:58:06,665 [INFO] Encountered issues in cluster. Hence, setting the go/no-go signal to false
2021-05-07 17:58:06,665 [INFO] Exception: 'conditions'
```
Trackback
```
Traceback (most recent call last):
  File "start_cerberus.py", line 308, in main
    if "Approved" not in csr['status']['conditions'][0]['type']:
```
Line 304 to 308
```
csrs = kubecli.get_csrs()
pending_csr = []
for csr in csrs['items']:
    # find csr status
    if "Approved" not in csr['status']['conditions'][0]['type']:
```
get_csrs() in client.py
```
def get_csrs():
    csr_string = runcommand.invoke("oc get csr -o yaml")
    csr_yaml = yaml.load(csr_string, Loader=yaml.FullLoader)
    return csr_yaml
```
I manually run oc get csr -o yaml against my cluster and got the output, below is a part of it. The `status` is blank.
```
% oc get csr -o yaml
apiVersion: v1
items:
- apiVersion: certificates.k8s.io/v1
  kind: CertificateSigningRequest
  metadata:
    creationTimestamp: "2021-05-07T09:00:25Z"
    generateName: csr-
    managedFields:
    - apiVersion: certificates.k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
      manager: aws-pod-identity-webhook
      operation: Update
      time: "2021-05-07T09:00:25Z"
    name: csr-4hlx4
    resourceVersion: "84948"
    uid: 5ab98b50-a5a0-4e8d-9d69-9411e3b46156
  spec:
    groups:
    - system:serviceaccounts
    - system:serviceaccounts:openshift-cloud-credential-operator
    - system:authenticated
    request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQi96Q0NBYVlDQVFBd1J6RkZNRU1HQTFVRUF4TThjRzlrTFdsa1pXNTBhWFI1TFhkbFltaHZiMnN1YjNCbApibk5vYVdaMExXTnNiM1ZrTFdOeVpXUmxiblJwWVd3dGIzQmxjbUYwYjNJdWMzWmpNRmt3RXdZSEtvWkl6ajBDCkFRWUlLb1pJemowREFRY0RRZ0FFRUtoOFpGcHZQSEF2MVNnalo3MkZIZk9lZDFaQWUzNWFJTGRSSStqNlU0NGoKRi8xazNsVFdIRUh6M3k4L2xaVDYzbFJPU1ZhbkVueko3L3I5VHFGbmU2Q0IvRENCK1FZSktvWklodmNOQVFrTwpNWUhyTUlIb01JSGxCZ05WSFJFRWdkMHdnZHFDRkhCdlpDMXBaR1Z1ZEdsMGVTMTNaV0pvYjI5cmdqaHdiMlF0CmFXUmxiblJwZEhrdGQyVmlhRzl2YXk1dmNHVnVjMmhwWm5RdFkyeHZkV1F0WTNKbFpHVnVkR2xoYkMxdmNHVnkKWVhSdmNvSThjRzlrTFdsa1pXNTBhWFI1TFhkbFltaHZiMnN1YjNCbGJuTm9hV1owTFdOc2IzVmtMV055WldSbApiblJwWVd3dGIzQmxjbUYwYjNJdWMzWmpna3B3YjJRdGFXUmxiblJwZEhrdGQyVmlhRzl2YXk1dmNHVnVjMmhwClpuUXRZMnh2ZFdRdFkzSmxaR1Z1ZEdsaGJDMXZjR1Z5WVhSdmNpNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQUsKQmdncWhrak9QUVFEQWdOSEFEQkVBaUJSbFZYUG1rNXVUT1BkRG5QK25RN0FPRDJQWTNVbm5jOFpuakk4TWRNdwo4UUlnTTRLMVQ1QnZ6UjJ2Q3M4ck42RCtDZE9jUnhLaytIclV3cFdISEZUT2V6ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
    signerName: kubernetes.io/legacy-unknown
    uid: 4528a0fc-93cc-426e-a2f8-f618c1097ce6
    usages:
    - digital signature
    - key encipherment
    - server auth
    username: system:serviceaccount:openshift-cloud-credential-operator:pod-identity-webhook
  status: {}
```
The whole json output `oc get csr -o json` is attached here [csr.txt](https://github.com/cloud-bulldozer/cerberus/files/6442386/csr.txt

**Comment by qiliRedHat** [comment] 2021-05-10 10:03
I did some investigation today, this may not be a valid issue. I used the latest internal build, this could be caused by a bug. I will follow up with the internal team and update here.

**Comment by paigerube14** [comment] 2021-05-12 19:37
This is caused by issue: https://bugzilla.redhat.com/show_bug.cgi?id=1958861

Still might be helpful to throw an error for csr's that don't have a proper status

**Comment by chaitanyaenr** [comment] 2021-06-15 12:49
@qiliRedHat Thanks for reporting the issue, @paigerube14 patched the code to handle the empty CSR conditions: https://github.com/cloud-bulldozer/cerberus/pull/141. Closing the issue but feel free to reopen if something needs to be changed. Thanks.

**Closed by chaitanyaenr** 2021-06-15 12:49 UTC
